version: '3'
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    depends_on:
      - rabbitmq

  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - celery-worker
    ports:
      - "8000:8000"
