# Base image
FROM python:3.8

# Set the working directory to /app
WORKDIR /app

# Copy only necessary files into the container
COPY . .

# Install required Python packages
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install celery

# Run the Celery worker by default
CMD ["celery", "-A", "tasks", "worker", "--loglevel=info", "--pool=solo"]
