FROM python:3.8

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir fastapi uvicorn requests scikit-learn

CMD ["uvicorn", "entrapeer_task:app", "--host", "0.0.0.0", "--port", "8000"]
